# example netlify.toml
[build]
  command = "npm run build"
  functions = ".functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
